### ISSUE TITLE
tab completion not working

### ISSUE THREAD

**Issue by kimpixel** [sandstorm/oh-my-zsh-flow-plugin#10]
I only get;
flow (eval):1: command not found: Could

Ubuntu Yakkety Yak

**Comment by mstruebing** [comment]
I also experience some tab-completion issues - will investigate soon what's wrong there

**Comment by bwaidelich** [comment]
Works for me(tm)

Mac OS

**Comment by skurfuerst** [comment]
should hopefully be fixed by #17 . Please reopen if not :)
