### ISSUE TITLE
Plugin installation with zplug

### ISSUE THREAD

**Issue by jonnitto** [sandstorm/oh-my-zsh-flow-plugin#16]
I tried to add the plugin with [zplug](https://github.com/zplug/zplug) like this in my `.zshrc`

```bash
zplug "sandstorm/oh-my-zsh-flow-plugin", from:oh-my-zsh
```
But this does not work. If I add it like this:

```bash
zplug "sandstorm/oh-my-zsh-flow-plugin"
```

The command `flow` work, but the tab completion does not work. I got the same error like in issue #10

**Comment by skurfuerst** [comment]
please re-open if #17 does not fix the issue :) Thanks!
